--[[                                                                           ]]--
--[[  Generated by FAF Map Editor                                              ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '0',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['ENEMY_BASE_EXP_2'] = {
            ['rectangle'] = RECTANGLE( 370, 400, 1024, 700 ),
        },
        ['ENEMY_BASE_EXP_1'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 370, 700 ),
        },
        ['M1_Playable_Area'] = {
            ['rectangle'] = RECTANGLE( 0, 700, 1024, 1024 ),
        },
        ['ENEMY_BASE_MAIN'] = {
            ['rectangle'] = RECTANGLE( 370, 0, 1024, 400 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Mass 16'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 51.5, 20.00122, 894.5001 ),
                },
                ['Hydrocarbon 03'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 40.5, 20.00122, 825.5 ),
                },
                ['Mass 00'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 403.5, 20.00122, 839.5001 ),
                },
                ['Mass 07'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 315.5, 20.00122, 917.5 ),
                },
                ['M1_UEFAlly_Attack_East_A_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 680.4999, 20.00122, 715.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 528.5, 20.00122, 755.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 442.5, 20.00122, 789.5001 ),
                },
                ['Mass 12'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 378.5, 20.00122, 730.5 ),
                },
                ['Mass 03'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 426.5, 20.00122, 772.5 ),
                },
                ['UEFAlly'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 442.5, 20.00122, 828.5001 ),
                },
                ['Mass 01'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 418.5, 20.00122, 859.5001 ),
                },
                ['M1_UEFAlly_Attack_East_B_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 659.5, 20.00122, 499.5 ),
                },
                ['Mass 04'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 478.5, 20.00122, 745.5 ),
                },
                ['Mass 06'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 605.5, 20.00122, 824.5001 ),
                },
                ['Mass 11'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 317.5, 20.00122, 870.5 ),
                },
                ['M1_UEFAlly_Attack_East_A_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 834.5, 20.62234, 568.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 542.5, 20.00122, 836.5 ),
                },
                ['Mass 17'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 67.5, 20.00122, 792.5 ),
                },
                ['Mass 14'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 318.5, 20.00122, 979.5001 ),
                },
                ['M1_UEFAlly_Base_Patrol_03'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 337.5, 20.00122, 768.5001 ),
                },
                ['M1_UEFAlly_Base_Patrol_04'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 257.5, 20.00122, 867.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 615.5, 20.00122, 819.5001 ),
                },
                ['Mass 02'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 470.5, 20.00122, 840.5 ),
                },
                ['M1_UEFAlly_Attack_East_B_04'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 822.5, 20.00122, 396.5 ),
                },
                ['Mass 10'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 316.5, 20.00122, 785.5 ),
                },
                ['Mass 05'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 540.5, 20.00122, 759.5001 ),
                },
                ['M1_UEFAlly_Attack_East_A_04'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 901.4999, 20.00122, 428.5 ),
                },
                ['M1_UEFAlly_Attack_East_A_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 517.5, 20.00122, 790.5 ),
                },
                ['Mass 13'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 604.5, 20.00122, 744.5001 ),
                },
                ['M1_UEFAlly_Attack_East_B_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 443.5, 20.00122, 711.5 ),
                },
                ['Mass 09'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 273.5, 20.00122, 841.5 ),
                },
                ['Player1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 279.5, 20.00122, 955.5 ),
                },
                ['Mass 15'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 106.5, 20.00122, 984.5001 ),
                },
                ['Hydrocarbon 02'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 345.5, 20.00122, 827.5 ),
                },
                ['M1_UEFAlly_Land_Patrol_A_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 586.5, 20.00122, 787.5 ),
                },
                ['M1_UEFAlly_Base_Patrol_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 442.5, 20.00122, 747.5 ),
                },
                ['M1_UEFAlly_Base_Patrol_01'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 529.5, 20.00122, 823.5001 ),
                },
                ['M1_UEFAlly_Attack_East_B_02'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 537.5, 20.00122, 569.5 ),
                },
                ['Mass 08'] = {
                    ['size'] = FLOAT( 1.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff808080' ),
                    ['editorIcon'] = STRING( '' ),
                    ['type'] = STRING( 'Mass' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 256.5, 20.00122, 926.5 ),
                },
                ['M1_South_Base_Marker'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 449.5, 20.00122, 828.5001 ),
                },
            },
        },
    },
    Chains = {
        ['M1_UEFAlly_Attack_East_A'] = {
            Markers = {
                "M1_UEFAlly_Attack_East_A_01",
                "M1_UEFAlly_Attack_East_A_02",
                "M1_UEFAlly_Attack_East_A_03",
                "M1_UEFAlly_Attack_East_A_04",
            },
        },
        ['M1_UEFAlly_Attack_East_B'] = {
            Markers = {
                "M1_UEFAlly_Attack_East_B_01",
                "M1_UEFAlly_Attack_East_B_02",
                "M1_UEFAlly_Attack_East_B_03",
                "M1_UEFAlly_Attack_East_B_04",
            },
        },
        ['M1_UEFAlly_Base_Patrol'] = {
            Markers = {
                "M1_UEFAlly_Base_Patrol_01",
                "M1_UEFAlly_Base_Patrol_02",
                "M1_UEFAlly_Base_Patrol_03",
                "M1_UEFAlly_Base_Patrol_04",
            },
        },
        ['M1_UEFAlly_Land_Patrol_A'] = {
            Markers = {
                "M1_UEFAlly_Land_Patrol_A_01",
                "M1_UEFAlly_Land_Patrol_A_02",
                "M1_UEFAlly_Land_Patrol_A_03",
            },
        },
    },
    next_queue_id = '0',
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    Orders = {
    },
    next_platoon_id = '0',
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    Platoons = {
    },
    next_army_id = '0',
    next_group_id = '0',
    next_unit_id = '0',
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies = {
        --[[                                                                           ]]--
        --[[  Player1                                                                  ]]--
        --[[                                                                           ]]--
        ['Player1'] = 
        {
            personality = '',
            plans = '/lua/ai/OpAI/DefaultBlankPlanlist.lua',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  UEFAlly                                                                  ]]--
        --[[                                                                           ]]--
        ['UEFAlly'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['M1_Land_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_31'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 456.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_34'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 462.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_32'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 458.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_33'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 460.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_35'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 464.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_38'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 462.5, 20.00122, 818.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_36'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 466.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_37'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 458.5, 20.00122, 818.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_39'] = {
                                type = 'uel0103',
                                orders = '',
                                platoon = '',
                                Position = { 460.5, 20.00122, 818.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_South_Base_D1'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['M1_South_Base_D2'] = GROUP {
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['M1_South_Base_D3'] = GROUP {
                                        orders = '',
                                        platoon = '',
                                        Units = {
                                            ['UNIT_1'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 433.5, 20.00122, 837.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_5'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 430.5, 20.00122, 828.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_8'] = {
                                                type = 'ueb1202',
                                                orders = '',
                                                platoon = '',
                                                Position = { 403.5, 20.00122, 839.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_12'] = {
                                                type = 'ueb2104',
                                                orders = '',
                                                platoon = '',
                                                Position = { 464.5, 20.00122, 806.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_2'] = {
                                                type = 'ueb1201',
                                                orders = '',
                                                platoon = '',
                                                Position = { 427.5, 20.00122, 836.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_0'] = {
                                                type = 'ueb0102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 425.5, 20.00122, 829.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_17'] = {
                                                type = 'ueb1105',
                                                orders = '',
                                                platoon = '',
                                                Position = { 440.5, 20.00122, 784.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_9'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 470.5, 20.00122, 840.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_11'] = {
                                                type = 'ueb2104',
                                                orders = '',
                                                platoon = '',
                                                Position = { 464.5, 20.00122, 828.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_3'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 430.5, 20.00122, 832.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_7'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 418.5, 20.00122, 859.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_4'] = {
                                                type = 'ueb1101',
                                                orders = '',
                                                platoon = '',
                                                Position = { 434.5, 20.00122, 832.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_13'] = {
                                                type = 'ueb2104',
                                                orders = '',
                                                platoon = '',
                                                Position = { 444.5, 20.00122, 768.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_10'] = {
                                                type = 'ueb1103',
                                                orders = '',
                                                platoon = '',
                                                Position = { 426.5, 20.00122, 772.5 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                            ['UNIT_6'] = {
                                                type = 'ueb1102',
                                                orders = '',
                                                platoon = '',
                                                Position = { 442.5, 20.00122, 789.5001 },
                                                Orientation = { 0, 0, 0 },
                                            },
                                        },
                                    },
                                    ['UNIT_19'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 438.5, 20.00122, 764.5001 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_16'] = {
                                        type = 'ueb3101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 432.5, 20.00122, 832.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_18'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 478.5, 20.00122, 798.5001 },
                                        Orientation = { 0, -4.712389, 0 },
                                    },
                                    ['UNIT_15'] = {
                                        type = 'ueb0102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 441.5, 20.00122, 797.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_14'] = {
                                        type = 'ueb0102',
                                        orders = '',
                                        platoon = '',
                                        Position = { 435.5, 20.00122, 789.5001 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                            ['UNIT_26'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 439.5, 20.00122, 813.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_22'] = {
                                type = 'ueb1102',
                                orders = '',
                                platoon = '',
                                Position = { 542.5, 20.00122, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_27'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 459.5, 20.00122, 783.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_24'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 552.5, 20.00122, 826.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_28'] = {
                                type = 'ueb2101',
                                orders = '',
                                platoon = '',
                                Position = { 576.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_29'] = {
                                type = 'ueb2101',
                                orders = '',
                                platoon = '',
                                Position = { 560.5, 20.00122, 794.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_20'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 542.5, 20.00122, 830.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_23'] = {
                                type = 'ueb1201',
                                orders = '',
                                platoon = '',
                                Position = { 537.5, 20.00122, 831.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_21'] = {
                                type = 'ueb0102',
                                orders = '',
                                platoon = '',
                                Position = { 536.5, 20.00122, 836.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_25'] = {
                                type = 'ueb2204',
                                orders = '',
                                platoon = '',
                                Position = { 527.5, 20.00122, 805.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_30'] = {
                                type = 'ueb2101',
                                orders = '',
                                platoon = '',
                                Position = { 524.5, 20.00122, 768.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_Bomber_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_51'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 424.5, 20.00122, 844.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_52'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 426.5, 20.00122, 844.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_53'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 428.5, 20.00122, 844.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_50'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 422.5, 20.00122, 844.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_49'] = {
                                type = 'uea0103',
                                orders = '',
                                platoon = '',
                                Position = { 420.5, 20.00122, 844.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_Land_Platoon_B'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_48'] = {
                                type = 'uel0103',
                                orders = '',
                                platoon = '',
                                Position = { 439.5, 20.00122, 757.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_42'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 439.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_47'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 441.5, 20.00122, 757.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_40'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 435.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_44'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 443.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_41'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 437.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_43'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 441.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_46'] = {
                                type = 'uel0101',
                                orders = '',
                                platoon = '',
                                Position = { 437.5, 20.00122, 757.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_45'] = {
                                type = 'uel0201',
                                orders = '',
                                platoon = '',
                                Position = { 445.5, 20.00122, 755.5 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                    ['M1_Interceptor_Platoon_A'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['UNIT_56'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 364.5, 20.00122, 814.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_57'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 366.5, 20.00122, 814.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_54'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 360.5, 20.00122, 814.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_55'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 362.5, 20.00122, 814.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_59'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 368.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_62'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 362.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_63'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 360.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_61'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 364.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_60'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 366.5, 20.00122, 816.5 },
                                Orientation = { 0, 0, 0 },
                            },
                            ['UNIT_58'] = {
                                type = 'uea0102',
                                orders = '',
                                platoon = '',
                                Position = { 368.5, 20.00122, 814.5001 },
                                Orientation = { 0, 0, 0 },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  CYBRANEnemy                                                              ]]--
        --[[                                                                           ]]--
        ['CYBRANEnemy'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_17                                                                  ]]--
        --[[                                                                           ]]--
        ['ARMY_17'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  NEUTRAL_CIVILIAN                                                         ]]--
        --[[                                                                           ]]--
        ['NEUTRAL_CIVILIAN'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
    },
}
